# Generated by Django 4.2.2 on 2023-07-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catdog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animalimage',
            old_name='creation_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='animalimage',
            old_name='type_of_img',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='animalimage',
            name='species',
            field=models.CharField(choices=[('cat', 'Kitten'), ('dog', 'Dog')], default='cat', max_length=5),
        ),
    ]
